wx:
  mp:
    useRedis: false
    redisConfig:
      host: bittechblog.com
      port: 6379
    configs:
      - appId: wx21eb36134e421873 # 第一个公众号的appid
        secret: 64d6d5297a25ee50ec23ee51a38a3db1 # 公众号的appsecret
        token: ncl1234 # 接口配置里的Token值
        aesKey: LsWuUafNY5Qx36rNAOTkemWkAcoJSCBBDL5FBTLybYZ # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111
#logging logback
logging:
  config: classpath:logback-spring.xml
  file: middleplat

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: repository.
 
spring:
  profiles:
    active:  dev
  redis:
    host: 129.28.178.8
    password: jackdking@1234
  datasource:
    url: jdbc:mysql://bittechblog.com:3308/middleplat?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: wanyang@wms
    driver-class-name: com.mysql.cj.jdbc.Driver
      