# 数据库配置
spring:
  main:
# sharding-jdbc定义了重复的dataSource数据源bean，启动时必须添加以下值
    allow-bean-definition-overriding: true
# sharding-jdbc 分库、分表配置
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2,ds3
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://10.18.93.13:3308/myutilproject0?characterEncoding=GBK&useSSL=false
#        username: root
#        password: jackdking@1234
        url: jdbc:mysql://bittechblog.com:3308/redpacket0?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms
        driver-class-name: com.mysql.jdbc.Driver
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://10.18.93.13:3308/myutilproject1?characterEncoding=GBK&useSSL=false
#        username: root
#        password: jackdking@1234
        url: jdbc:mysql://bittechblog.com:3308/redpacket1?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms
        driver-class-name: com.mysql.jdbc.Driver
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://10.18.93.13:3308/myutilproject0?characterEncoding=GBK&useSSL=false
#        username: root
#        password: jackdking@1234
        url: jdbc:mysql://bittechblog.com:3308/redpacket2?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms
        driver-class-name: com.mysql.jdbc.Driver
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://10.18.93.13:3308/myutilproject1?characterEncoding=GBK&useSSL=false
#        username: root
#        password: jackdking@1234
        url: jdbc:mysql://bittechblog.com:3308/redpacket3?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms
        driver-class-name: com.mysql.jdbc.Driver
    sharding:
      tables:
        roncoo_redpacket_info:
          actual-data-nodes: ds$->{0..3}.roncoo_redpacket_info$->{0..7}
          database-strategy:
            standard:
              precise-algorithm-class-name: com.sohu.common.algorithm.SuperDbShardingAlgorithm
              sharding-column: PS_TRANS_ID
          table-strategy:
            standard:
              precise-algorithm-class-name: com.sohu.common.algorithm.SuperTableShardingAlgorithm
              sharding-column: PS_TRANS_ID
#            inline:
#              #分片规则对应列，即以user_id值作为分片规则的列
#              sharding-column: orderid
#              #分片按user_id列和10取模运算，路由到对应的order0...9的表
#              algorithm-expression: TransInfo$->{orderid % 2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#      default-database-strategy:
#        standard:
#          precise-algorithm-class-name: org.jackdking.shardjdbcyaml.algorithm.SuperTableShardingAlgorithm
#          sharding-column: orderid
#        inline:
#          sharding-column: id
#          algorithm-expression: ds$->{id % 2}
    props:
      sql.show: true      
          
    redis: 
        database: 0 
        #host: 192.168.64.224 
        #host: 192.168.0.101 
        #password: a*#sIYn$iP#Rvx&*rEdIs$%^%z 
        host: localhost
        password:  
        port: 6379 
        #port: 6479 
        #port: 6379 
        pool: 
            max-idle: 100 
            min-idle: 100 
            max-active: 100     
renewal: 
        status: start
        keys: redpacket_renewal_key
        time: 30
        step: 5
redpacket: 
        batch: 100
        waitTime: 5000
        testTime: 5000
        testWaitTime: 5000
block: 
     queue: 
        corepoolsize: 30
        maxpoolsize: 30
        allow: true 
        keepalivetime: 60
        queuecapacity: 60
#javamelody
#    init-parameters: 
#        log: true 
#        authorized-users: wallet:abc123456 
#        storage-directory: ${log.path.prefix}/javamelody 
#        monitoring-path: /see 
stats: 
    projectName: wallet-redservice.test
    ip: 10.11.152.59
    port: 8125